Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -31,17 +31,19 @@ phases:
       - sonar-scanner --version
 
   build:
-    commands:
-      - sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
-      - sleep 30
-      - curl -s -u "$LOGIN:" "$HOST/api/qualitygates/project_status?projectKey=$Project" > result.json
-      - |
-        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
-          echo "❌ Quality Gate failed"
-          exit 1
-        else
-          echo "✅ Quality Gate passed"
-        fi
+     commands:
+      - echo "Waiting for SonarCloud automatic analysis to complete..."
+      - sleep 10  # Adjust based on expected time for analysis completion
+      - echo "Checking Quality Gate status..."
+      - curl -u "$LOGIN:" "$HOST/api/qualitygates/project_status?projectKey=$Project" > result.json
+      - cat result.json
+      - |
+        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
+          echo "❌ Quality Gate failed"
+          exit 1
+        else
+          echo "✅ Quality Gate passed"
+        fi
 
 artifacts:
   files:
