Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -15,7 +15,7 @@ phases:
     commands:
       - yum update -y
       - yum install -y jq unzip
-      - python -m venv venv  # LINE 18 (NO TABS/HIDDEN CHARACTERS)
+      - python -m venv venv
       - source venv/bin/activate
       - pip install --upgrade pip
       - pip install -r requirements.txt
@@ -31,19 +31,19 @@ phases:
       - sonar-scanner --version
 
   build:
-     commands:
-      - echo "Waiting for SonarCloud automatic analysis to complete..."
-      - sleep 10  # Adjust based on expected time for analysis completion
-      - echo "Checking Quality Gate status..."
-      - curl -u "$LOGIN:" "$HOST/api/qualitygates/project_status?projectKey=$Project" > result.json
-      - cat result.json
-      - |
-          if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
-            echo "❌ Quality Gate failed"
-            exit 1
-          else
-            echo "✅ Quality Gate passed"
-          fi
+    commands:
+      - echo "Waiting for SonarCloud automatic analysis to complete..."
+      - sleep 10  # Adjust based on expected time for analysis completion
+      - echo "Checking Quality Gate status..."
+      - curl -u "$LOGIN:" "$HOST/api/qualitygates/project_status?projectKey=$Project" > result.json
+      - cat result.json
+      - |
+        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
+          echo "❌ Quality Gate failed"
+          exit 1
+        else
+          echo "✅ Quality Gate passed"
+        fi
 
 artifacts:
   files:
