Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -38,12 +38,12 @@ phases:
       - curl -u "$LOGIN:" "$HOST/api/qualitygates/project_status?projectKey=$Project" > result.json
       - cat result.json
       - |
-        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
-          echo "❌ Quality Gate failed"
-          exit 1
-        else
-          echo "✅ Quality Gate passed"
-        fi
+          if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
+            echo "❌ Quality Gate failed"
+            exit 1
+          else
+            echo "✅ Quality Gate passed"
+          fi
 
 artifacts:
   files:
